### ISSUE TITLE
Sprint 6.1. C. Import a hierarchy of Hops (Warehouse, Truck, TransferWarehouse) objects.

### ISSUE THREAD

**Issue by variableVG** [variableVG/swkom_project#127]
![Image](https://user-images.githubusercontent.com/58001220/205673747-bb203dba-c508-433b-a02c-91ecac8b97d5.png)

**Comment by i-nazuma** [comment]
Hey vio,
in the stackoverflow link they get the same problem, since the compiler doesn't like blindly typecasting into a subclass.

The solution is to use ` if (hop instanceof WarehouseEntity)` before casting, since this provides some kind of safety check for the compiler. But hop is only of type HopEntity, so this will never work in our case.

I implemented a workaround by creating a manual caster method that maps all attributes from the original HopEntity to a WarehouseEntity. I'm not sure if thats a good solution, but it worked in my test run. Check out my commit to your branch.

**Comment by i-nazuma** [comment]
![Image](https://user-images.githubusercontent.com/71130765/207183130-9abaff66-8437-40d0-8ed1-ec8c28878776.png)

**Comment by variableVG** [comment]
I watch your code, but this does not really work. If we use the small json from moodle, we should get 5 warehouses and several trucks in the DB. 

The reason why the toWarehouse method **does not work:** It gives back an empty list of WarehouseNextHopsEntity and therefore it just does not give down the whole information about the rest of warehouses. The first warehouse is recognized as a warehouse, and the second warehouse is recognized as an entity, that then is converted to a warehouse but with an empty list. This does not solve our problem!

I think the main problem is that Springboot takes the Jsons, and since in the WarehouseNextHopsEntity the Hops are defined as Hops, the json is directly transform in a hop and not in a Warehousedto or Truckdto.

**Comment by variableVG** [comment]
I have also written a function: checkWhatIsInWarehouse() to debug this problem. Maybe this would help understand how to deal with it ....
